name: ci

on:
  push:
    branches:
      - main
jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/weather-station:latest

  build-yocto:
    runs-on: ubuntu-latest
    needs: publish-docker
    steps:
      -
        name: Checkout source code
        uses: actions/checkout@v3
      -
        name: Check disk space
        run: |
          df -h
          du -sh /usr
          du -sh /opt
          du -sh $AGENT_TOOLSDIRECTORY
      -
        name: Set up aritfact directory
        run: |
          mkdir -p ${{ github.workspace }}/artifacts
          chmod 777 ${{ github.workspace }}/artifacts
      -
        name: Set up Docker
        run: |
          docker run \
          --rm \
          -v ${{ github.workspace }}:/workspace \
          -w /yocto \
          ${{ vars.DOCKERHUB_USERNAME }}/weather-station:latest \
          bash -c "
            source openembedded-core/oe-init-build-env;
            cp /workspace/conf/local.conf conf/local.conf;
            cp /workspace/conf/bblayers.conf conf/bblayers.conf;
            bitbake core-image-minimal;
            ls -l /yocto/build/tmp-glibc/deploy/images/raspberrypi5/
            cp /yocto/build/tmp-glibc/deploy/images/raspberrypi5/*.wic.bz2 /workspace/artifacts;
            cp /yocto/build/tmp-glibc/deploy/images/raspberrypi5/*.wic.bmap /workspace/artifacts;
          "
      -
        name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: yocto-output
          path: ${{ github.workspace }}/artifacts/*
